version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=patientdb
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - springboot-network

  springboot-app:
    build: .
    restart: on-failure
    image: patient-app:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/patientdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on: [mariadb]
    networks:
      - springboot-network

networks:
  springboot-network:
    external: true
